version: 2

project_name: agit

before:
  hooks:
    - go mod tidy

builds:
  - id: agit
    main: .
    binary: agit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/fathindos/agit/cmd.Version={{.Version}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

brews:
  - repository:
      owner: Fato07
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: agit-bot
      email: bot@agit.dev
    directory: Formula
    homepage: "https://github.com/Fato07/agit"
    description: "Infrastructure-aware Git orchestration for AI agents"
    license: "MIT"
    install: |
      bin.install "agit"
    test: |
      system "#{bin}/agit", "--version"

release:
  github:
    owner: Fato07
    name: agit
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

nfpms:
  - id: packages
    package_name: agit
    vendor: Fato07
    homepage: https://github.com/Fato07/agit
    description: "Infrastructure-aware Git orchestration for AI agents"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
